/*
 * Copyright 2026 Aethernet Inc.
 *
 * Experiment Wi-Fi driver variant flags (compile-time).
 */
#ifndef AETHER_AE_EXP_WIFI_H_
#define AETHER_AE_EXP_WIFI_H_

#ifndef AE_EXP_WIFI_CANONICAL
#define AE_EXP_WIFI_CANONICAL 0
#endif
#ifndef AE_EXP_WIFI_FEAT_AMPDU_OFF
#define AE_EXP_WIFI_FEAT_AMPDU_OFF 0
#endif
#ifndef AE_EXP_WIFI_FEAT_SCAN_THRESHOLD
#define AE_EXP_WIFI_FEAT_SCAN_THRESHOLD 0
#endif
#ifndef AE_EXP_WIFI_FEAT_CONNECT_RETRY10
#define AE_EXP_WIFI_FEAT_CONNECT_RETRY10 0
#endif
#ifndef AE_EXP_WIFI_FEAT_FAIL_DISCONNECT
#define AE_EXP_WIFI_FEAT_FAIL_DISCONNECT 0
#endif
#ifndef AE_EXP_WIFI_FEAT_BSSID_CACHE
#define AE_EXP_WIFI_FEAT_BSSID_CACHE 0
#endif
#ifndef AE_EXP_WIFI_FEAT_LEGACY_DEINIT
#define AE_EXP_WIFI_FEAT_LEGACY_DEINIT 0
#endif
#ifndef AE_EXP_WIFI_FEAT_LEGACY_HANDLERS
#define AE_EXP_WIFI_FEAT_LEGACY_HANDLERS 0
#endif
/* Experimental: ignore persisted/cached BSSID on Connect (keep type/state). */
#ifndef AE_EXP_WIFI_IGNORE_BSSID
#define AE_EXP_WIFI_IGNORE_BSSID 0
#endif

#if AE_EXP_WIFI_CANONICAL
#define AE_WIFI_USE_AMPDU_OFF AE_EXP_WIFI_FEAT_AMPDU_OFF
#define AE_WIFI_USE_SCAN_THRESHOLD AE_EXP_WIFI_FEAT_SCAN_THRESHOLD
#define AE_WIFI_USE_CONNECT_RETRY10 AE_EXP_WIFI_FEAT_CONNECT_RETRY10
#define AE_WIFI_USE_FAIL_DISCONNECT AE_EXP_WIFI_FEAT_FAIL_DISCONNECT
#define AE_WIFI_USE_BSSID_CACHE AE_EXP_WIFI_FEAT_BSSID_CACHE
#define AE_WIFI_USE_FULL_DEINIT (!AE_EXP_WIFI_FEAT_LEGACY_DEINIT)
#define AE_WIFI_USE_INSTANCE_HANDLERS (!AE_EXP_WIFI_FEAT_LEGACY_HANDLERS)
#else
#define AE_WIFI_USE_AMPDU_OFF 1
#define AE_WIFI_USE_SCAN_THRESHOLD 1
#define AE_WIFI_USE_CONNECT_RETRY10 1
#define AE_WIFI_USE_FAIL_DISCONNECT 1
#if AE_EXP_WIFI_IGNORE_BSSID
#define AE_WIFI_USE_BSSID_CACHE 0
#else
#define AE_WIFI_USE_BSSID_CACHE 1
#endif
#define AE_WIFI_USE_FULL_DEINIT 0
#define AE_WIFI_USE_INSTANCE_HANDLERS 0
#endif

#endif  // AETHER_AE_EXP_WIFI_H_
