name: cpplint

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --recursive ./aether
    - run: cpplint --recursive ./tests

